interface Ward {
  name: string;
}

interface District {
  name: string;
  wards: Ward[];
}

interface City {
  city: string;
  districts: District[];
}
const API = [
  {
    city: "Hà Nội",
    districts: [
      {
        name: "Quận Hoàn Kiếm",
        wards: [
          "Phường Hàng Bạc",
          "Phường Hàng Đào",
          "Phường Cửa Đông",
          "Phường Hàng Bồ",
          "Phường Đồng Xuân",
        ],
      },
      {
        name: "Quận Ba Đình",
        wards: [
          "Phường Phúc Xá",
          "Phường Vĩnh Phúc",
          "Phường Cống Vị",
          "Phường Kim Mã",
          "Phường Đội Cấn",
        ],
      },
      {
        name: "Quận Đống Đa",
        wards: [
          "Phường Trung Liệt",
          "Phường Trung Tự",
          "Phường Văn Chương",
          "Phường Khâm Thiên",
          "Phường Ngã Tư Sở",
        ],
      },
      {
        name: "Quận Tây Hồ",
        wards: [
          "Phường Xuân La",
          "Phường Nhật Tân",
          "Phường Quảng An",
          "Phường Thụy Khuê",
          "Phường Tây Hồ",
        ],
      },
      // Add more districts and wards here
    ],
  },
  {
    city: "Hồ Chí Minh",
    districts: [
      {
        name: "Quận 1",
        wards: [
          "Phường Bến Nghé",
          "Phường Bến Thành",
          "Phường Nguyễn Thái Bình",
          "Phường Cô Giang",
          "Phường Đa Kao",
        ],
      },
      {
        name: "Quận 2",
        wards: [
          "Phường An Phú",
          "Phường Bình An",
          "Phường Thảo Điền",
          "Phường An Khánh",
          "Phường Cát Lái",
        ],
      },
      {
        name: "Quận 3",
        wards: [
          "Phường Võ Thị Sáu",
          "Phường Nguyễn Thị Minh Khai",
          "Phường 6",
          "Phường 7",
          "Phường 8",
        ],
      },
      {
        name: "Quận 4",
        wards: ["Phường 1", "Phường 2", "Phường 3", "Phường 4", "Phường 5"],
      },
      // Add more districts and wards here
    ],
  },
  {
    city: "Đà Nẵng",
    districts: [
      {
        name: "Quận Hải Châu",
        wards: [
          "Phường Thạch Thang",
          "Phường Hòa Thuận Đông",
          "Phường Hòa Cường Bắc",
          "Phường Nam Dương",
          "Phường Bình Thuận",
        ],
      },
      {
        name: "Quận Sơn Trà",
        wards: [
          "Phường An Hải Bắc",
          "Phường An Hải Tây",
          "Phường An Hải Đông",
          "Phường Mân Thái",
          "Phường Nại Hiên Đông",
        ],
      },
      {
        name: "Quận Ngũ Hành Sơn",
        wards: [
          "Phường Mỹ An",
          "Phường Mỹ Khe",
          "Phường Hòa Quý",
          "Phường Hòa Hải",
          "Phường Hòa Phát",
        ],
      },
      {
        name: "Huyện Hòa Vang",
        wards: [
          "Xã Hòa Phong",
          "Xã Hòa Sơn",
          "Xã Hòa Tiến",
          "Xã Hòa Khương",
          "Xã Hòa Nhơn",
        ],
      },
      // Add more districts and wards here
    ],
  },
  {
    city: "Cần Thơ",
    districts: [
      {
        name: "Quận Ninh Kiều",
        wards: [
          "Phường An Cư",
          "Phường An Hòa",
          "Phường An Bình",
          "Phường Cái Khế",
          "Phường Cái Răng",
        ],
      },
      {
        name: "Quận Bình Thủy",
        wards: [
          "Phường Bình Thủy",
          "Phường Long Hòa",
          "Phường Trà An",
          "Phường Trà Nóc",
          "Phường Bùi Hữu Nghĩa",
        ],
      },
      {
        name: "Quận Cái Răng",
        wards: [
          "Phường Hưng Phú",
          "Phường Lê Bình",
          "Phường Thường Thạnh",
          "Phường Thường Thới",
          "Phường Trường Lạc",
        ],
      },
      {
        name: "Huyện Ô Môn",
        wards: [
          "Xã Thới Hòa",
          "Xã Thới Tam Thôn",
          "Xã Thới Đông",
          "Xã Thới Long",
          "Xã Thới Xuân",
        ],
      },
      // Add more districts and wards here
    ],
  },
  // Add more cities, districts, and wards here
];

export default API;

interface Laptop {
  name: string;
  price: number;
  brand: string;
  CPU: string;
  RAM: string;
  GPU: string;
  Storage: string;
  Screen: string;
  Resolution: string;
  Battery: string;
  Weight: string;
  category: string;
}

// Laptop data
const APILAPTOP: Laptop[] = [
  {
    name: "Dell XPS 15",
    price: 25000000,
    brand: "Dell",
    CPU: "Intel Core i7-13700H",
    RAM: "16GB",
    GPU: "NVIDIA GeForce RTX 4050",
    Storage: "1TB SSD",
    Screen: "15.6 inch",
    Resolution: "3840x2400",
    Battery: "86Wh",
    Weight: "2.0 kg",
    category: "graphics",
  },
  {
    name: "Asus ROG Zephyrus G14",
    price: 21000000,
    brand: "Asus",
    CPU: "AMD Ryzen 9 5900HS",
    RAM: "32GB",
    GPU: "NVIDIA GeForce RTX 3060",
    Storage: "512GB SSD",
    Screen: "14 inch",
    Resolution: "2560x1600",
    Battery: "76Wh",
    Weight: "1.7 kg",
    category: "gaming",
  },
  {
    name: "Apple MacBook Pro 16",
    price: 35000000,
    brand: "Apple",
    CPU: "Apple M2 Max",
    RAM: "32GB",
    GPU: "Apple M2 Max GPU",
    Storage: "1TB SSD",
    Screen: "16.2 inch",
    Resolution: "3456x2234",
    Battery: "100Wh",
    Weight: "2.1 kg",
    category: "graphics",
  },
  {
    name: "HP Omen 17",
    price: 27000000,
    brand: "HP",
    CPU: "Intel Core i9-13900K",
    RAM: "32GB",
    GPU: "NVIDIA GeForce RTX 4070",
    Storage: "1TB SSD",
    Screen: "17.3 inch",
    Resolution: "2560x1440",
    Battery: "83Wh",
    Weight: "3.1 kg",
    category: "gaming",
  },
  {
    name: "Lenovo ThinkPad X1 Carbon",
    price: 23000000,
    brand: "Lenovo",
    CPU: "Intel Core i7-1365U",
    RAM: "16GB",
    GPU: "Intel Iris Xe",
    Storage: "512GB SSD",
    Screen: "14 inch",
    Resolution: "1920x1200",
    Battery: "57Wh",
    Weight: "1.1 kg",
    category: "graphics",
  },
  {
    name: "Acer Predator Helios 300",
    price: 22000000,
    brand: "Acer",
    CPU: "Intel Core i7-12700H",
    RAM: "16GB",
    GPU: "NVIDIA GeForce RTX 3060",
    Storage: "512GB SSD",
    Screen: "15.6 inch",
    Resolution: "1920x1080",
    Battery: "59Wh",
    Weight: "2.5 kg",
    category: "gaming",
  },
  {
    name: "Microsoft Surface Laptop Studio",
    price: 29000000,
    brand: "Microsoft",
    CPU: "Intel Core i7-11370H",
    RAM: "32GB",
    GPU: "NVIDIA GeForce RTX 3050 Ti",
    Storage: "1TB SSD",
    Screen: "14.4 inch",
    Resolution: "2400x1600",
    Battery: "58Wh",
    Weight: "1.8 kg",
    category: "graphics",
  },
  {
    name: "Gigabyte Aorus 15G",
    price: 26000000,
    brand: "Gigabyte",
    CPU: "Intel Core i7-11800H",
    RAM: "16GB",
    GPU: "NVIDIA GeForce RTX 3070",
    Storage: "1TB SSD",
    Screen: "15.6 inch",
    Resolution: "1920x1080",
    Battery: "99Wh",
    Weight: "2.2 kg",
    category: "gaming",
  },
  {
    name: "Razer Blade 15 Advanced",
    price: 32000000,
    brand: "Razer",
    CPU: "Intel Core i9-12900H",
    RAM: "32GB",
    GPU: "NVIDIA GeForce RTX 3080 Ti",
    Storage: "1TB SSD",
    Screen: "15.6 inch",
    Resolution: "3840x2160",
    Battery: "80Wh",
    Weight: "2.1 kg",
    category: "gaming",
  },
  {
    name: "MSI Creator Z16",
    price: 28000000,
    brand: "MSI",
    CPU: "Intel Core i9-11900H",
    RAM: "32GB",
    GPU: "NVIDIA GeForce RTX 3060",
    Storage: "1TB SSD",
    Screen: "16 inch",
    Resolution: "2560x1600",
    Battery: "90Wh",
    Weight: "2.0 kg",
    category: "graphics",
  },
  {
    name: "Samsung Galaxy Book Pro 360",
    price: 20000000,
    brand: "Samsung",
    CPU: "Intel Core i7-1165G7",
    RAM: "16GB",
    GPU: "Intel Iris Xe",
    Storage: "512GB SSD",
    Screen: "13.3 inch",
    Resolution: "1920x1080",
    Battery: "63Wh",
    Weight: "1.0 kg",
    category: "graphics",
  },
  {
    name: "HP Spectre x360",
    price: 24000000,
    brand: "HP",
    CPU: "Intel Core i7-1255U",
    RAM: "16GB",
    GPU: "Intel Iris Xe",
    Storage: "1TB SSD",
    Screen: "13.5 inch",
    Resolution: "3000x2000",
    Battery: "66Wh",
    Weight: "1.3 kg",
    category: "graphics",
  },
  {
    name: "Lenovo Legion 5 Pro",
    price: 26000000,
    brand: "Lenovo",
    CPU: "AMD Ryzen 7 5800H",
    RAM: "16GB",
    GPU: "NVIDIA GeForce RTX 3070",
    Storage: "512GB SSD",
    Screen: "16 inch",
    Resolution: "2560x1600",
    Battery: "80Wh",
    Weight: "2.5 kg",
    category: "gaming",
  },
  {
    name: "MSI GE76 Raider",
    price: 33000000,
    brand: "MSI",
    CPU: "Intel Core i9-11980HK",
    RAM: "32GB",
    GPU: "NVIDIA GeForce RTX 3080",
    Storage: "1TB SSD",
    Screen: "17.3 inch",
    Resolution: "3840x2160",
    Battery: "99Wh",
    Weight: "3.0 kg",
    category: "gaming",
  },
  {
    name: "Acer Swift X",
    price: 20000000,
    brand: "Acer",
    CPU: "AMD Ryzen 7 5800U",
    RAM: "16GB",
    GPU: "NVIDIA GeForce RTX 3050 Ti",
    Storage: "512GB SSD",
    Screen: "14 inch",
    Resolution: "1920x1080",
    Battery: "59Wh",
    Weight: "1.4 kg",
    category: "graphics",
  },
  {
    name: "Dell Inspiron 14 5000",
    price: 19000000,
    brand: "Dell",
    CPU: "Intel Core i5-1235U",
    RAM: "8GB",
    GPU: "Intel Iris Xe",
    Storage: "512GB SSD",
    Screen: "14 inch",
    Resolution: "1920x1080",
    Battery: "53Wh",
    Weight: "1.6 kg",
    category: "general",
  },
  {
    name: "Gigabyte Aero 16",
    price: 27000000,
    brand: "Gigabyte",
    CPU: "Intel Core i7-12700H",
    RAM: "16GB",
    GPU: "NVIDIA GeForce RTX 3060",
    Storage: "1TB SSD",
    Screen: "16.1 inch",
    Resolution: "3840x2160",
    Battery: "76Wh",
    Weight: "2.1 kg",
    category: "graphics",
  },
  {
    name: "Samsung Notebook 9 Pro",
    price: 21000000,
    brand: "Samsung",
    CPU: "Intel Core i7-1165G7",
    RAM: "16GB",
    GPU: "Intel Iris Xe",
    Storage: "512GB SSD",
    Screen: "15 inch",
    Resolution: "1920x1080",
    Battery: "54Wh",
    Weight: "1.9 kg",
    category: "graphics",
  },
  {
    name: "Asus TUF Gaming A15",
    price: 22000000,
    brand: "Asus",
    CPU: "AMD Ryzen 7 4800H",
    RAM: "16GB",
    GPU: "NVIDIA GeForce GTX 1660 Ti",
    Storage: "512GB SSD",
    Screen: "15.6 inch",
    Resolution: "1920x1080",
    Battery: "48Wh",
    Weight: "2.3 kg",
    category: "gaming",
  },
  {
    name: "HP Elite Dragonfly",
    price: 30000000,
    brand: "HP",
    CPU: "Intel Core i7-8665U",
    RAM: "16GB",
    GPU: "Intel UHD Graphics 620",
    Storage: "512GB SSD",
    Screen: "13.5 inch",
    Resolution: "1920x1080",
    Battery: "56Wh",
    Weight: "0.99 kg",
    category: "general",
  },
  {
    name: "Razer Blade Stealth 13",
    price: 25000000,
    brand: "Razer",
    CPU: "Intel Core i7-1165G7",
    RAM: "16GB",
    GPU: "NVIDIA GeForce GTX 1650 Ti",
    Storage: "512GB SSD",
    Screen: "13.3 inch",
    Resolution: "1920x1080",
    Battery: "53Wh",
    Weight: "1.4 kg",
    category: "gaming",
  },
  {
    name: "Lenovo IdeaPad Slim 7",
    price: 20000000,
    brand: "Lenovo",
    CPU: "AMD Ryzen 7 5800U",
    RAM: "16GB",
    GPU: "AMD Radeon Graphics",
    Storage: "512GB SSD",
    Screen: "14 inch",
    Resolution: "1920x1080",
    Battery: "57Wh",
    Weight: "1.4 kg",
    category: "general",
  },
  {
    name: "Huawei MateBook X Pro",
    price: 23000000,
    brand: "Huawei",
    CPU: "Intel Core i7-1165G7",
    RAM: "16GB",
    GPU: "Intel Iris Xe",
    Storage: "1TB SSD",
    Screen: "13.9 inch",
    Resolution: "3000x2000",
    Battery: "56Wh",
    Weight: "1.33 kg",
    category: "graphics",
  },
  {
    name: "Dell G5 15",
    price: 22000000,
    brand: "Dell",
    CPU: "Intel Core i7-10750H",
    RAM: "16GB",
    GPU: "NVIDIA GeForce GTX 1650 Ti",
    Storage: "512GB SSD",
    Screen: "15.6 inch",
    Resolution: "1920x1080",
    Battery: "51Wh",
    Weight: "2.5 kg",
    category: "gaming",
  },
  {
    name: "MSI Modern 14",
    price: 19000000,
    brand: "MSI",
    CPU: "Intel Core i5-1135G7",
    RAM: "8GB",
    GPU: "Intel Iris Xe",
    Storage: "256GB SSD",
    Screen: "14 inch",
    Resolution: "1920x1080",
    Battery: "52Wh",
    Weight: "1.3 kg",
    category: "general",
  },
  {
    name: "Acer Aspire 7",
    price: 20000000,
    brand: "Acer",
    CPU: "AMD Ryzen 5 3550H",
    RAM: "8GB",
    GPU: "NVIDIA GeForce GTX 1650",
    Storage: "512GB SSD",
    Screen: "15.6 inch",
    Resolution: "1920x1080",
    Battery: "37Wh",
    Weight: "2.3 kg",
    category: "gaming",
  },
  {
    name: "Lenovo Yoga 7i",
    price: 24000000,
    brand: "Lenovo",
    CPU: "Intel Core i7-1165G7",
    RAM: "16GB",
    GPU: "Intel Iris Xe",
    Storage: "1TB SSD",
    Screen: "14 inch",
    Resolution: "1920x1080",
    Battery: "60Wh",
    Weight: "1.5 kg",
    category: "graphics",
  },
  {
    name: "Asus ZenBook 14",
    price: 21000000,
    brand: "Asus",
    CPU: "Intel Core i7-1165G7",
    RAM: "16GB",
    GPU: "Intel Iris Xe",
    Storage: "512GB SSD",
    Screen: "14 inch",
    Resolution: "1920x1080",
    Battery: "67Wh",
    Weight: "1.3 kg",
    category: "general",
  },
  {
    name: "HP Pavilion x360",
    price: 20000000,
    brand: "HP",
    CPU: "Intel Core i5-1135G7",
    RAM: "8GB",
    GPU: "Intel Iris Xe",
    Storage: "512GB SSD",
    Screen: "14 inch",
    Resolution: "1920x1080",
    Battery: "43Wh",
    Weight: "1.58 kg",
    category: "graphics",
  },
  {
    name: "Gigabyte Aorus 17G",
    price: 28000000,
    brand: "Gigabyte",
    CPU: "Intel Core i7-11800H",
    RAM: "32GB",
    GPU: "NVIDIA GeForce RTX 3070",
    Storage: "1TB SSD",
    Screen: "17.3 inch",
    Resolution: "1920x1080",
    Battery: "99Wh",
    Weight: "2.9 kg",
    category: "gaming",
  },
  {
    name: "Samsung Galaxy Book 3 Pro",
    price: 25000000,
    brand: "Samsung",
    CPU: "Intel Core i7-13700H",
    RAM: "16GB",
    GPU: "Intel Iris Xe",
    Storage: "512GB SSD",
    Screen: "14.6 inch",
    Resolution: "2880x1800",
    Battery: "63Wh",
    Weight: "1.2 kg",
    category: "graphics",
  },
  {
    name: "Razer Blade 17",
    price: 34000000,
    brand: "Razer",
    CPU: "Intel Core i9-12900H",
    RAM: "32GB",
    GPU: "NVIDIA GeForce RTX 3080 Ti",
    Storage: "1TB SSD",
    Screen: "17.3 inch",
    Resolution: "3840x2160",
    Battery: "80Wh",
    Weight: "2.8 kg",
    category: "gaming",
  },
  {
    name: "Dell Latitude 7420",
    price: 27000000,
    brand: "Dell",
    CPU: "Intel Core i7-1185G7",
    RAM: "16GB",
    GPU: "Intel Iris Xe",
    Storage: "512GB SSD",
    Screen: "14 inch",
    Resolution: "1920x1080",
    Battery: "60Wh",
    Weight: "1.3 kg",
    category: "general",
  },
  // Add more laptops as needed
];
